"""create_discovery_snapshots_table

Revision ID: 357df49c7f3d
Revises: 89665d24d492
Create Date: 2026-07-20 10:54:24.143179

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "357df49c7f3d"
down_revision: Union[str, Sequence[str], None] = "89665d24d492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("hostname", sa.String(), nullable=False),
        sa.Column("operating_system", sa.String(), nullable=False),
        sa.Column("kernel_version", sa.String(), nullable=False),
        sa.Column("architecture", sa.String(), nullable=False),
        sa.Column("uptime", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("cpu", sa.JSON(), nullable=False),
        sa.Column("memory", sa.JSON(), nullable=False),
        sa.Column("disks", sa.JSON(), nullable=False),
        sa.Column("network_interfaces", sa.JSON(), nullable=False),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_snapshots_id"), "discovery_snapshots", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_discovery_snapshots_server_id"),
        "discovery_snapshots",
        ["server_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_discovery_snapshots_server_id"), table_name="discovery_snapshots"
    )
    op.drop_index(op.f("ix_discovery_snapshots_id"), table_name="discovery_snapshots")
    op.drop_table("discovery_snapshots")
    # ### end Alembic commands ###
