"""create_telemetry_metrics_table

Revision ID: 4493fda53116
Revises: df7946e80bd4
Create Date: 2026-07-20 11:15:18.305810

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4493fda53116"
down_revision: Union[str, Sequence[str], None] = "df7946e80bd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("metric_type", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telemetry_metrics_id"), "telemetry_metrics", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_metrics_metric_type"),
        "telemetry_metrics",
        ["metric_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_metrics_server_id"),
        "telemetry_metrics",
        ["server_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_metrics_timestamp"),
        "telemetry_metrics",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telemetry_metrics_timestamp"), table_name="telemetry_metrics"
    )
    op.drop_index(
        op.f("ix_telemetry_metrics_server_id"), table_name="telemetry_metrics"
    )
    op.drop_index(
        op.f("ix_telemetry_metrics_metric_type"), table_name="telemetry_metrics"
    )
    op.drop_index(op.f("ix_telemetry_metrics_id"), table_name="telemetry_metrics")
    op.drop_table("telemetry_metrics")
    # ### end Alembic commands ###
