"""create_incidents_tables

Revision ID: 8dbc17948c07
Revises: d911b1279f24
Create Date: 2026-07-20 11:29:19.123945

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dbc17948c07"
down_revision: Union[str, Sequence[str], None] = "d911b1279f24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column("resolution_notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incidents_created_at"), "incidents", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_incidents_id"), "incidents", ["id"], unique=False)
    op.create_index(
        op.f("ix_incidents_server_id"), "incidents", ["server_id"], unique=False
    )
    op.create_table(
        "incident_timeline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_timeline_id"), "incident_timeline", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_incident_timeline_incident_id"),
        "incident_timeline",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_timeline_timestamp"),
        "incident_timeline",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_incident_timeline_timestamp"), table_name="incident_timeline"
    )
    op.drop_index(
        op.f("ix_incident_timeline_incident_id"), table_name="incident_timeline"
    )
    op.drop_index(op.f("ix_incident_timeline_id"), table_name="incident_timeline")
    op.drop_table("incident_timeline")
    op.drop_index(op.f("ix_incidents_server_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_created_at"), table_name="incidents")
    op.drop_table("incidents")
    # ### end Alembic commands ###
