"""create_server_health_table

Revision ID: d911b1279f24
Revises: 4493fda53116
Create Date: 2026-07-20 11:24:18.909770

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d911b1279f24"
down_revision: Union[str, Sequence[str], None] = "4493fda53116"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server_health",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("overall_status", sa.String(), nullable=False),
        sa.Column("health_score", sa.Float(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("evaluation_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_server_health_evaluation_timestamp"),
        "server_health",
        ["evaluation_timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_server_health_id"), "server_health", ["id"], unique=False)
    op.create_index(
        op.f("ix_server_health_server_id"), "server_health", ["server_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_server_health_server_id"), table_name="server_health")
    op.drop_index(op.f("ix_server_health_id"), table_name="server_health")
    op.drop_index(
        op.f("ix_server_health_evaluation_timestamp"), table_name="server_health"
    )
    op.drop_table("server_health")
    # ### end Alembic commands ###
