"""create_inventory_table

Revision ID: df7946e80bd4
Revises: 357df49c7f3d
Create Date: 2026-07-20 11:06:44.643394

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df7946e80bd4"
down_revision: Union[str, Sequence[str], None] = "357df49c7f3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("hostname", sa.String(), nullable=False),
        sa.Column("operating_system", sa.String(), nullable=False),
        sa.Column("kernel_version", sa.String(), nullable=False),
        sa.Column("architecture", sa.String(), nullable=False),
        sa.Column("uptime", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("cpu", sa.JSON(), nullable=False),
        sa.Column("memory", sa.JSON(), nullable=False),
        sa.Column("disks", sa.JSON(), nullable=False),
        sa.Column("network_interfaces", sa.JSON(), nullable=False),
        sa.Column("last_discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("project", sa.String(), nullable=True),
        sa.Column("business_unit", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("datacenter", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("criticality", sa.String(), nullable=True),
        sa.Column("connector_type", sa.String(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_environment"), "inventory", ["environment"], unique=False
    )
    op.create_index(op.f("ix_inventory_id"), "inventory", ["id"], unique=False)
    op.create_index(
        op.f("ix_inventory_project"), "inventory", ["project"], unique=False
    )
    op.create_index(op.f("ix_inventory_region"), "inventory", ["region"], unique=False)
    op.create_index(op.f("ix_inventory_role"), "inventory", ["role"], unique=False)
    op.create_index(
        op.f("ix_inventory_server_id"), "inventory", ["server_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_server_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_role"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_region"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_project"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_environment"), table_name="inventory")
    op.drop_table("inventory")
    # ### end Alembic commands ###
